<?php

namespace Database\Seeders;

use App\Models\Setting;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Super Admin',
            'email' => 'test@example.com',
            'password' => Hash::make('Nepal@123'),
        ]);
        // Define settings data
        $settings = [
            ['site_main_logo', null],
            ['site_fav_icon', null],
            ['site_information', 'Empowering students with expert guidance for academic success. Your trusted partner in achieving educational goals.'],
            ['site_phone', '9848484848'],
            ['site_email', 'hanamiconsultancy@gmail.com'],
            ['site_location', 'Kathmandu, Nepal'],
            ['site_location_url', 'https://paradiseinfo.tech/'],
            ['site_map', 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11131.78490171464!2d85.339818!3d27.694685!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb199a06c2eaf9%3A0xc5670a9173e161de!2sNew%20Baneshwor%2C%20Kathmandu%2044600%2C%20Nepal!5e1!3m2!1sen!2sus!4v1733377392963!5m2!1sen!2sus'],
            ['site_url', null],
            ['site_copyright', 'hanami consultancy'],
            ['features_title', 'WHY CHOOSE US !!!'],
            ['service_image', null],
            ['feature_description', 'We’re proud of our award-winning track record and 99% success rate. Our personalized guidance, global connections, and all-inclusive support—from applications to visas—make studying abroad a breeze. With our 100% client satisfaction guarantee and 24/7 support, we’re here for you every step of the way. Choose us for a smooth and successful study abroad experience!'],
            ['about_image_1', 'frontend/img/about-2.png'],
            ['about_image_2', 'frontend/img/about-3.jpg'],
            ['about_image_3', 'frontend/img/about-2.png'],
            ['about_image_4', 'frontend/img/about-3.jpg'],
            ['about_title', 'About the Company'],
            ['about_description', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt architecto consectetur...'],
            ['about_feature_1_icon', 'fas fa-map-marked-alt'],
            ['about_feature_1_text', 'Best Immigration Resources'],
            ['about_feature_2_icon', 'fas fa-passport'],
            ['about_feature_2_text', 'Return Visas Available'],
            ['about_years_of_experience', '5'],
            ['about_stat_description', 'Years of Experience'],
            ['about_highlights', ['Offer 100% Genuine Assistance', 'It’s Faster & Reliable Execution', 'Accurate & Expert Advice']], // Array instead of JSON string
            ['about_phone_icon', 'fa fa-phone-alt'],
            ['about_phone_label', 'Have any questions?'],
            ['about_phone_number', '977-15339150'],
            ['about_title_2', 'About the Company'],
            ['about_description_2', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt architecto consectetur...'],
            ['about_feature_1_icon_2', 'fas fa-map-marked-alt'],
            ['about_feature_1_text_2', 'Best Immigration Resources'],
            ['about_feature_2_icon_2', 'fas fa-passport'],
            ['about_feature_2_text_2', 'Return Visas Available'],
            ['about_years_of_experience_2', '34'],
            ['about_stat_description_2', 'Years of Experience'],
            ['about_highlights_2', ['Offer 100% Genuine Assistance', 'It’s Faster & Reliable Execution', 'Accurate & Expert Advice']], // Array instead of JSON string
            ['about_phone_icon_2', 'fa fa-phone-alt'],
            ['about_phone_label_2', 'Have any questions?'],
            ['about_phone_number_2', '977-15339150'],
            ['welcome_description', '<h1 class="display-5 mb-4" style="color:rgb(21, 36, 64);">Welcome To <strong>CONSULT</strong></h1><h4 class="text-primary mb-4">Provides expert guidance and support to students seeking to pursue higher education abroad.</h4><p>We assist with selecting the right courses, applying to universities, securing visas, and offering personalized counseling to help students achieve their academic and career goals in top international institutions.</p>'],
            ['quote_formtitle', 'Request A Free Quote'],
            ['quote_formimage', null],
            ['quote_formdescription', 'Get started on your journey to studying abroad with ease! Request a free quote today to learn more about our personalized services and how we can assist you in achieving your educational goals. Simply fill out the form, and our team will provide you with a detailed, no-obligation quote tailored to your needs. Let us help you turn your study abroad dreams into reality!'],
            ['blog_title', 'Recent Post'],
            ['abroad_quotetitle', 'Request A Free Quote'],
            ['abroad_quotedescription', 'Get started on your journey to studying abroad with ease! Request a free quote today to learn more about our personalized services and how we can assist you in achieving your educational goals. Simply fill out the form, and our team will provide you with a detailed, no-obligation quote tailored to your needs. Let us help you turn your study abroad dreams into reality!'],
            ['abroad_quoteimage', null],
            ['contact_title', 'Contact Us'],
            ['contact_image', null],
            ['service_quotetitle', 'Request A Free Quote'],
            ['service_quoteimage', null],
            ['service_quotedescription', 'Get started on your journey to studying abroad with ease! Request a free quote today to learn more about our personalized services and how we can assist you in achieving your educational goals. Simply fill out the form, and our team will provide you with a detailed, no-obligation quote tailored to your needs. Let us help you turn your study abroad dreams into reality!'],
            ['contactform_title', 'Interested In Study Abroad?'],
            ['member_image', null],
            ['blogs_title', 'Latest Blog Posts'],
            ['blogs_image', null],
            ['quote_title', 'Request A Free Quote'],
            ['quote_image', null],
            ['quote_description', 'We assist with selecting the right courses, applying to universities, securing visas, and offering personalized counseling to help students achieve their academic and career goals in top international institutions.'],
            ['scholorship_image', null],
            ['blogs_description', 'Watch Our Recent Blogs'],
            ['testimonials_title', 'What Our Students Say!'],
            ['testimonials_image', null],
            ['testimonials_description', 'What They Say About Us'],
            ['getintouch_description', '<p>We are dedicated to providing personalized educational solutions, enhancing learning outcomes, and supporting students in their academic journeys.</p>'],
            ['review_image', null],
            ['abroads_title', 'Study Abroad'],
            ['abroads_description', 'We assist with selecting the right courses, applying to universities, securing visas, and offering personalized counseling to help students achieve their academic and career goals in top international institutions.'],
            ['service_title', 'What We Offer'],
            ['abroads_seo_description', 'Study Abroad'],
            ['abroads_seo_keywords', 'Study Abroad'],
            ['abroads_seo_title', 'Study Abroad'],
            ['service_seo_description', 'Services'],
            ['service_seo_keywords', 'Services'],
            ['service_seo_title', 'Services'],
            ['blogs_seo_keywords', 'Abroad Blogs'],
            ['blogs_seo_description', 'Blogs'],
            ['blogs_seo_title', 'Blog'],
            ['homepage_seo_keywords', 'Homepage'],
            ['homepage_seo_description', 'Homepage'],
            ['homepage_seo_title', 'Home'],
            ['about_seo_keywords', 'About Us Page'],
            ['about_seo_description', 'About Us page'],
            ['about_seo_title', 'About Us'],
            ['team_seo_keywords', 'Teams Page'],
            ['team_seo_description', 'Our Team Page'],
            ['team_seo_title', 'Our Team'],
            ['testimonial_seo_keywords', 'Testimonial'],
            ['testimonial_seo_description', 'Testimonial'],
            ['testimonial_seo_title', 'Testimonial'],
            ['features_seo_keywords', 'Features'],
            ['features_seo_description', 'Features'],
            ['features_seo_title', 'Features'],
            ['quote_seo_keywords', 'Free Quote'],
            ['quote_seo_description', 'Free Quote'],
            ['quote_seo_title', 'Free Quote'],
            ['blogs_seo_schema', 'Abroad Blogs'],
            ['services_seo_schema', 'Your JSON-LD schema data here'],
            ['homepage_seo_schema', 'Homepage'],
            ['about_seo_schema', 'About Us page'],
            ['team_seo_schema', 'Our Team Page'],
            ['testimonial_seo_schema', 'Testimonial'],
            ['features_seo_schema', 'Features'],
            ['quote_seo_schema', 'Free Quote'],
            ['abroads_seo_schema', 'Study Abroad'],
            ['service_seo_schema', 'Services'],
            ['contact_seo_title', 'Contact Us'],
            ['contact_seo_description', 'Contact Us'],
            ['contact_seo_keywords', 'Contact Us'],
            ['contact_seo_schema', 'Contact Us'],
            ['blog_quotetitle', 'Request A Free Quote'],
            ['blog_quoteimage', null],
            ['blog_quotedescription', 'Get started on your journey to studying abroad with ease! Request a free quote today to learn more about our personalized services and how we can assist you in achieving your educational goals. Simply fill out the form, and our team will provide you with a detailed, no-obligation quote tailored to your needs. Let us help you turn your study abroad dreams into reality!'],
            ['faqs_seo_title', 'Frequently Asked Questions'],
            ['faqs_seo_description', 'Frequently Asked Questions'],
            ['faqs_seo_keywords', 'Frequently Asked Questions'],
            ['faqs_seo_schema', 'Frequently Asked Questions'],
            ['site_footer_logo', null],
            ['testimonial_title', 'OUR CLIENTS RIVIEWS'],
            ['course_title', 'CHECK OUR COURSE'],
            ['team_title', 'Our Teams'],
            ['contact_quick_title', 'Have Questions? Dont Hesitate to Contact Us'],
            ['contact_quick_description', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat totam deserunt tempora. Tempore neque necessitatibus corporis error earum sint quae?'],
            ['contact_quick_location', 'Location'],
            ['contact_quick_locationtitle', '123, First Floor, 123 St Roots Terrace, Los Angeles 90010 Unitd States of America.'],
            ['contact_quick_location_icon', 'fas fa-map-marked-alt'],
            ['contact_description', 'Welcome to Aktone! You can contact us or apply to become a member by clicking the register button.'],
            ['course_seo_title', 'Best Online Courses | Learn & Grow with Expert-Led Training'],
            ['course_seo_keywords', 'online courses, professional training, e-learning, best courses, skill development, certification courses'],
            ['course_seo_schema', 'online courses, professional training, e-learning, best courses, skill development, certification courses'],
            ['course_seo_description', 'Discover expert-led online courses covering various fields to enhance your skills and career. Join now for professional training and certification.'],
            ['site_breadcrumb_banner', null],
            ['approved_footer_banner', null],
            ['proud_member_footer_banner', null],
        ];
        // Insert settings data
        foreach ($settings as $item) {
            Setting::create([
                'key' => $item[0],
                'value' => $item[1],
            ]);
        }
    }
}
